---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: madwyatt/spring-docker
        ports:
        - containerPort: 8080